# Approved exceptions
cves:
  - CVE-2021-12345
  - CVE-2020-67890

# Approved risky dependencies
dependencies:
  - package: legacy-package
    version: 1.2.3
    reason: Required for legacy integration